src/DotNetCoreWebApp/ViewModels/ArtistViewModel.cs
using System.Collections.Generic;
using DotNetCoreWebAppModels.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DotNetCoreWebApp.ViewModels
{
    public class ArtistViewModel : BaseViewModel
    {
        public ArtistViewModel()
        {
            ArtistsList = new List<Artist>();
        }
        public IEnumerable<Artist> ArtistsList { get; set; }

        override public List<SelectListItem> SortColumns
        {
            get
            {
                var list = new List<SelectListItem>
                {
                    new SelectListItem {Text = "Artist Id", Value = "ArtistId"},
                    new SelectListItem {Text = "Artist name", Value = "Name"}
                };
                return list;
            }
        }

    }
}

src/DotNetCoreWebApp/Controllers/Api/ArtistsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Core.Common.Data.Models;
using DotNetCoreWebApp.Controllers.Api;
using DotNetCoreWebAppBusiness.Business.Interfaces;
using DotNetCoreWebAppModels.Models;
using Microsoft.AspNetCore.Mvc;

namespace DotNetCoreWebApp.Controllers.Api
{
    [Route("api/[controller]")]
    public sealed class ArtistsController : BaseApiController
    {

        private readonly IArtistEntityBusiness _artistEntityBusiness;

        public ArtistsController(
            IArtistEntityBusiness artistEntityBusiness)
        {
            _artistEntityBusiness = artistEntityBusiness;
        }


        [HttpGet]
        [Route("{id:int}")]
        public async Task<IActionResult> FindById(int id)
        {
            var artist = await _artistEntityBusiness.FindEntityById(id);
            return Json(artist);
        }
        


        [HttpGet]
        [Route("")]
        public IActionResult GetAll(
            int? pageNumber, int? pageSize, string sortCol,
            string sortDir, string searchTerms)
        {

            OperationResult result = _artistEntityBusiness.ListItems(
                pageNumber, pageSize, sortCol, sortDir, searchTerms);


            var paginationData = new PaginationData
            {
                OffsetFromZero = (int)result.ObjectsDictionary["offset"],
                PageNumber = (int)result.ObjectsDictionary["pageIndex"],
                PageSize = (int)result.ObjectsDictionary["sizeOfPage"],
                OffsetUpperBound = (int)result.ObjectsDictionary["offsetUpperBound"],
                TotalNumberOfRecords = (int)result.ObjectsDictionary["totalNumberOfRecords"],
                TotalNumberOfPages = (int)result.ObjectsDictionary["totalNumberOfPages"],
                SearchTermsCommaSeparated = result.ObjectsDictionary["searchTerms"].ToString(),
                SortColumn = result.ObjectsDictionary["sortCol"].ToString(),
                SortDirection = result.ObjectsDictionary["sortDir"].ToString()
            };
            var list = result.ObjectsDictionary["list"] as IEnumerable<Artist>;
            var toReturn = Json(new { list, paginationData });

            return toReturn;
        }

    }
}

src/DotNetCoreWebApp/Controllers/ChinookController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Core.Common.Data.Interfaces;
using Core.Common.Data.Models;
using DotNetCoreWebApp.EditModels;
using DotNetCoreWebApp.ViewModels;
using DotNetCoreWebAppBusiness.Business.Interfaces;
using DotNetCoreWebAppModels.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace DotNetCoreWebApp.Controllers
{

    public class ChinookController : BaseController
    {
        private readonly IArtistEntityBusiness _artistEntityBusiness;

        public ChinookController(
             IArtistEntityBusiness artistEntityBusiness, IHostingEnvironment hostingEnvironment)
        {
            _artistEntityBusiness = artistEntityBusiness;
            this.hostingEnvironment = hostingEnvironment;

        }

        public IActionResult Artists(
            int? pageNumber, int? pageSize, string sortCol,
            string sortDir, string searchTerms)
        {
            return ExecuteExceptionsHandledActionResult(() =>
            {
                OperationResult result = _artistEntityBusiness.ListItems(
                pageNumber, pageSize, sortCol, sortDir, searchTerms);

                ViewBag.offset = result.ObjectsDictionary["offset"];
                ViewBag.pageIndex = result.ObjectsDictionary["pageIndex"];
                ViewBag.sizeOfPage = result.ObjectsDictionary["sizeOfPage"];
                ViewBag.offsetUpperBound = result.ObjectsDictionary["offsetUpperBound"];
                ViewBag.totalRecords = result.ObjectsDictionary["totalNumberOfRecords"];
                ViewBag.totalNumberOfPages = result.ObjectsDictionary["totalNumberOfPages"];
                ViewBag.searchTerms = result.ObjectsDictionary["searchTerms"];
                ViewBag.sortCol = result.ObjectsDictionary["sortCol"];
                ViewBag.sortDir = result.ObjectsDictionary["sortDir"];

                var model = new ArtistViewModel {ArtistsList = result.ObjectsDictionary["list"] as IEnumerable<Artist>};

                return View(model);
            });
        }

        public IActionResult EditArtist(int id)
        {
            return ExecuteExceptionsHandledActionResult(() =>
          {
              return View();
          });
        }

        public IActionResult AddArtist()
        {
            return ExecuteExceptionsHandledActionResult(() =>
          {
              return View();
          });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddArtist(ArtistEditModel model)
        {
            if (model == null) return View();

            return await ExecuteExceptionsHandledAsyncActionResult(async () =>
            {
                var artist = new Artist
                {
                    Name = model.Name,
                    ObjectState = ObjectState.Added,
                    Deleted = false
                };
                await _artistEntityBusiness.PersistEntity(artist);
                return View(model);
            });
        }

        public IActionResult ArtistsAngular()
        {
            return View();
        }

        public ActionResult AppPath()
        {
            string webRootPath = hostingEnvironment.WebRootPath;
            string contentRootPath = hostingEnvironment.ContentRootPath;

            return Content(webRootPath + "\n" + contentRootPath);
        }
    }
}

src/DotNetCoreWebApp/ViewComponents/ListPagerViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DotNetCoreWebApp.ViewComponents
{
    public class ListPagerViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(
            string controllerName,
            string controllerAction,            
            int totalNumberOfItems, 
            int pageNumber, 
            int pageSize,
            int totalNumberOfPages,
            int offset, 
            int offsetUpperBound,
            string sortCol,
            string sortDir,
            string searchTerms)
        {
            ViewBag.offset = offset;
            ViewBag.pageNumber = pageNumber;
            ViewBag.pageSize = pageSize;
            ViewBag.offsetUpperBound = offsetUpperBound;
            ViewBag.totalRecords = totalNumberOfItems;
            ViewBag.sortCol = sortCol;
            ViewBag.sorDir = sortDir;
            ViewBag.searchTerms = searchTerms;
            ViewBag.url = $"{Url.Content("~/")}{controllerName}/{controllerAction}";
                        
            return await Task.FromResult(View());
        }
    }
}

src/DotNetCoreWebApp/Views/Chinook/AddArtist.cshtml
@model DotNetCoreWebApp.EditModels.ArtistEditModel

<br /> <br />
<form asp-controller="Chinook" 
      asp-action="AddArtist">

      <label asp-for="Name">Name</label>
    <input asp-for="Name" />

    <input type="submit" value="Save" />    

</form>

src/DotNetCoreWebApp/Views/Chinook/Artists.cshtml
@model DotNetCoreWebApp.ViewModels.ArtistViewModel

@{
    ViewData["Title"] = "Items";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<a href="/Chinook/AddArtist">Add item</a>



@if(Model == null)
{
    <div>Sorry there was a probleam loading data from the database.</div>
} else
{
    if(Model.ArtistsList.Count() > 0)
    {
    <table class="table">
    <tr>
        <th>Artist Id</th>
        <th>Name</th>
        <th>Albums count</th>
    </tr>
    @foreach (var artist in Model.ArtistsList)
    {
        <tr>
            <td>
               @artist.ArtistId
            </td>
            <td>
               @artist.Name
            </td>
            <td>
                @artist.Album.Count()
            </td>
        </tr>
    }

    </table>
    }
    else 
    {
        <div>Sorry, there is nothing to show!</div>
    }
<form asp-controller="Chinook" asp-action="Artists" method="GET">
    <label asp-for="SearchTerms">Search terms (separated by comma)</label>
    <input asp-for="SearchTerms" />
    

    <label asp-for="SortCol">Sort column</label>
    <select asp-for="SortCol" asp-items="Model.SortColumns" > </select>
    <label asp-for="SortDir">Sort Direction</label>
    <select asp-for="SortDir" asp-items="Model.SortDirections" > </select>

    <input type="submit" value="Search" />    
    
</form>
    @await Component.InvokeAsync("ListPager", 
            new {
                controllerName = "Chinook", 
                controllerAction = "Artists", 
                totalNumberOfItems = ViewBag.totalRecords, 
                pageNumber = ViewBag.pageIndex,
                pageSize = ViewBag.sizeOfPage, 
                totalNumberOfPages = ViewBag.totalNumberOfPages, 
                offset =  ViewBag.offset,
                offsetUpperBound = ViewBag.offsetUpperBound,
                searchTerms = ViewBag.searchTerms,   
                sortCol = ViewBag.sortCol,
                sortDir = ViewBag.sortDir
            })
}



    

src/DotNetCoreWebApp/Views/Chinook/EditArtist.cshtml
<br />
<artist> <i class="fa fa-spin fa-circle-o-notch"></i>Loading...</artist>


@section scripts {
    @await Html.PartialAsync("_Angular2ScriptsImport.cshtml", "app/components/artists/artist-edit.component")      
}